[project]
name = "nlp-demo"
version = "0.1.0"
description = "手动实现经典NLP模型算法"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3",
    "numpy>=2",
]

[dependency-groups]
dev = [
    "ipykernel>=6",
]
